spring:
  application:
    name: demo
  datasource:
    url: jdbc:postgresql://localhost:5433/sonar  # PostgreSQL local sur 5433
    username: postgres
    password: mhd02042017
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8081  # L'application écoute sur 8081
